# Common vars
availability_zone: melbourne-qh2-uom

# Volume
volumes:
  - vol_name: vol-couchdb-1
    vol_size: 80
  - vol_name: vol-couchdb-2
    vol_size: 80
  - vol_name: vol-couchdb-3
    vol_size: 80

# Security group
security_groups:
  - name: ssh_ingress
    description: Allow ssh from external hosts
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: http_ingress
    description: Allow http from external hosts
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0
  - name: couchdb_ingress
    description: Allow couchdb clustering between hosts
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984
    remote_ip_prefix: 0.0.0.0/0

# Instance
instances:
  - name: couchdb-1
    volumes: ['vol-couchdb-1']
  - name: couchdb-2
    volumes: ['vol-couchdb-1']
  - name: couchdb-3
    volumes: ['vol-couchdb-1']

instance_image: 215f9775-483c-4e0a-b703-d21a5c966f2e
instance_key_name: couchdb
instance_flavor: uom.mse.1c4g

