#  2020 COMP90024 Team 49

---
    - name: Install CouchDB on all instances
      hosts: servers
      remote_user: ubuntu
      become: yes
    
      roles:
        - couchdb
        - cluster
        - harvester