# 2020 COMP90024 Project2
# Simon Cozens 1071589
# Solmaz Maabi 871603


- hosts: localhost
  vars_files:
    - host_vars/nectar.yaml
  gather_facts: true

  roles:
    - role: openstack-common
    - role: openstack-volume
    - role: openstack-security-group
    - role: openstack-instance

- hosts: team49
  vars_files:
    - host_vars/harvester.yaml

  roles:
    - role: th-common
#    - role: th-volumes
    - role: th-docker
    - role: install-couchdb
    - role: th-harvester
