---
- name: Create Harvester directory
  tags: 'harvester'
  become: yes
  file:
    path: "{{ th_dir }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    recurse: yes
    state: directory

- name: Configure compose
  tags: 'harvester'
  become: yes
  template:
    src: docker-compose.yaml
    dest: "{{ th_dir }}/docker-compose.yaml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Run docker compose
  tags: 'harvester'
  become: yes
  docker_compose:
    project_src: "{{ th_dir }}"
    pull: yes
    state: present
    remove_orphans: yes
    recreate: always